CREATE TABLE `credentials` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`host` text NOT NULL,
	`username` text NOT NULL,
	`password` text NOT NULL,
	`last_used` text DEFAULT (current_timestamp) NOT NULL,
	`created_at` text DEFAULT (current_timestamp) NOT NULL,
	`updated_at` text DEFAULT (current_timestamp) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `credentials_host_unique` ON `credentials` (`host`);--> statement-breakpoint
CREATE TABLE `heartbeats` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`monitor_id` integer NOT NULL,
	`down_count` integer NOT NULL,
	`duration` real NOT NULL,
	`important` integer NOT NULL,
	`status` integer NOT NULL,
	`msg` text NOT NULL,
	`ping` real NOT NULL,
	`time` text NOT NULL,
	`created_at` text DEFAULT (current_timestamp) NOT NULL,
	FOREIGN KEY (`monitor_id`) REFERENCES `monitor`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `info` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`is_container` integer DEFAULT false NOT NULL,
	`latest_version` text NOT NULL,
	`primary_base_url` text,
	`server_timezone` text NOT NULL,
	`server_timezone_offset` text NOT NULL,
	`version` text NOT NULL,
	`updated_at` text DEFAULT (current_timestamp) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `monitor_tags` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`monitor_id` integer NOT NULL,
	`tag_id` integer NOT NULL,
	`value` text,
	FOREIGN KEY (`monitor_id`) REFERENCES `monitor`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`tag_id`) REFERENCES `tags`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `monitor` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`type` text,
	`description` text,
	`pathName` text,
	`status` text,
	`weight` integer DEFAULT 1 NOT NULL,
	`parent` integer,
	`childrenIDs` text DEFAULT '[]' NOT NULL,
	`active` integer DEFAULT true NOT NULL,
	`forceInactive` integer DEFAULT false NOT NULL,
	`maintenance` integer DEFAULT false NOT NULL,
	`interval` integer,
	`timeout` integer DEFAULT 1,
	`maxretries` integer DEFAULT 0 NOT NULL,
	`retryInterval` integer DEFAULT 10 NOT NULL,
	`resendInterval` integer DEFAULT 0 NOT NULL,
	`upsideDown` integer DEFAULT false NOT NULL,
	`notificationIDList` text,
	`url` text,
	`method` text,
	`headers` text,
	`body` text,
	`httpBodyEncoding` text,
	`ignoreTls` integer,
	`maxredirects` integer,
	`proxyId` integer,
	`acceptedStatuscodes` text,
	`authMethod` text,
	`authDomain` text,
	`authWorkstation` text,
	`basicAuthUser` text,
	`basicAuthPass` text,
	`oauth_auth_method` text,
	`oauth_client_id` text,
	`oauth_client_secret` text,
	`oauth_token_url` text,
	`oauth_scopes` text,
	`tlsCa` text,
	`tlsCert` text,
	`tlsKey` text,
	`hostname` text,
	`dnsResolveServer` text,
	`dnsResolveType` text,
	`dns_last_result` text,
	`port` integer,
	`packetSize` integer,
	`dockerHost` text,
	`dockerContainer` text,
	`databaseConnectionString` text,
	`databaseQuery` text,
	`mqttUsername` text,
	`mqttPassword` text,
	`mqttTopic` text,
	`mqttSuccessMessage` text,
	`mqttCheckType` text,
	`keyword` text,
	`invertKeyword` integer,
	`jsonPath` text,
	`jsonPathOperator` text,
	`expectedValue` text,
	`browser_width` integer,
	`browser_height` integer,
	`remote_browser` integer,
	`radiusUsername` text,
	`radiusPassword` text,
	`radiusSecret` text,
	`radiusCalledStationId` text,
	`radiusCallingStationId` text,
	`kafkaProducerBrokers` text,
	`kafkaProducerTopic` text,
	`kafkaProducerMessage` text,
	`kafkaProducerSsl` integer,
	`kafkaProducerAllowAutoTopicCreation` integer,
	`kafkaProducerSaslOptions` text,
	`grpcUrl` text,
	`grpcProtobuf` text,
	`grpcServiceName` text,
	`grpcMethod` text,
	`grpcBody` text,
	`grpcMetadata` text,
	`grpcEnableTls` integer,
	`game` text,
	`gamedigGivenPortOnly` integer,
	`pushToken` text,
	`rabbitmqNodes` text,
	`rabbitmqUsername` text,
	`rabbitmqPassword` text,
	`snmpOid` text,
	`snmpVersion` text,
	`cacheBust` integer,
	`screenshot` text,
	`conditions` text,
	`includeSensitiveData` integer,
	`expiryNotification` integer,
	`created_at` text DEFAULT (current_timestamp) NOT NULL,
	`updated_at` text DEFAULT (current_timestamp) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `status` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`url` text NOT NULL,
	`is_external` integer DEFAULT false,
	`monitors` text,
	`updated_at` text DEFAULT (current_timestamp) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `status_url_unique` ON `status` (`url`);--> statement-breakpoint
CREATE TABLE `tags` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`color` text NOT NULL
);
