name: Android Build Preview APK

on:
  push:
    branches:
      - development
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip-build]') }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.x.x
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Get pnpm Store Directory
        id: pnpm-store
        run: |
          echo "store-path=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pnpm-store.outputs.store-path }}
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-pnpm-

      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.0.0

      - name: Cache Android Build
        uses: actions/cache@v4
        with:
          path: |
            **/build
          key: ${{ runner.os }}-android-build-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-build-

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: pnpm install

      - name: Build Android App
        id: build
        run: |
          eas build --platform android --profile staging --local --output ${{ github.workspace }}/app-release.apk

      - name: Upload APK Artifact
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.apk
          retention-days: 7

      - name: Read Version from package.json
        id: read_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: Create Git Tag
        if: steps.build.outcome == 'success'
        id: create_tag
        run: |
          TAG_NAME=v${{ steps.read_version.outputs.version }}-preview-${{ github.run_number }}
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: steps.build.outcome == 'success'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.read_version.outputs.version }}-preview-${{ github.run_number }}"
          release_name:  "v${{ steps.read_version.outputs.version }}-preview-${{ github.run_number }}"
          draft: false
          prerelease: true

      - name: Upload APK to Release
        if: steps.build.outcome == 'success'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive